Repository Azure/aad-pod-identity, pull requests merged in 2020-05, with the labels that each got.

#592 docs: document required role assignments
  README.md
  docs/readmes/README.md
  docs/readmes/README.msi.md
  docs/readmes/README.role-assignment.md
Labels: documentation

#596 fix: fix e2e test regression caused by #579
  test/common/azure/azure.go
  test/e2e/aadpodidentity_test.go
Labels: test improvement

#593 feat: add finalizer for assigned identity
  pkg/crd/crd.go
  pkg/crd/crd_test.go
  pkg/mic/mic.go
  pkg/mic/mic_test.go
Labels: enhancement

#598 chore: make cloud config configurable in helm chart
  charts/aad-pod-identity/README.md
  charts/aad-pod-identity/templates/mic-deployment.yaml
  charts/aad-pod-identity/values.yaml
Labels: enhancement

#590 feat: re-initialize MIC cloud client when cloud config is updated
  go.mod
  go.sum
  pkg/cloudprovider/cloudprovider.go
  pkg/filewatcher/filewatcher.go
  pkg/filewatcher/filewatcher_test.go
  pkg/mic/mic.go
Labels: enhancement

#597 Code clean up
  .pipelines/unit-tests-template.yml
  CHANGELOG-1.5.md
  CHANGELOG-1.6.md
  Dockerfile
  README.md
  charts/aad-pod-identity/README.md
  cmd/demo/main.go
  cmd/mic/main.go
  cmd/nmi/main.go
  cmd/simple/main.go
  docs/readmes/README.troubleshooting.md
  docs/tutorial/README.md
  pkg/apis/aadpodidentity/types.go
  pkg/apis/aadpodidentity/v1/conversion.go
  pkg/apis/aadpodidentity/v1/conversion_test.go
  pkg/apis/aadpodidentity/v1/types.go
  pkg/auth/auth.go
  pkg/cloudprovider/cloudprovider.go
  pkg/cloudprovider/cloudprovider_test.go
  pkg/cloudprovider/identity.go
  pkg/cloudprovider/identity_test.go
  pkg/cloudprovider/vm.go
  pkg/cloudprovider/vmss.go
  pkg/crd/crd.go
  pkg/crd/crd_test.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/fake.go
  pkg/metrics/metrics.go
  pkg/metrics/metrics_test.go
  pkg/metrics/prometheus_exporter.go
  pkg/mic/mic.go
  pkg/mic/mic_test.go
  pkg/mic/vmss.go
  pkg/nmi/iptables/iptables.go
  pkg/nmi/managed.go
  pkg/nmi/managed_test.go
  pkg/nmi/nmi.go
  pkg/nmi/server/server.go
  pkg/nmi/standard.go
  pkg/nmi/standard_test.go
  pkg/pod/pod.go
  pkg/pod/pod_test.go
  pkg/probes/probes.go
  pkg/stats/stats.go
  pkg/stats/stats_test.go
  pkg/utils/utils.go
  test/common/k8s/azureassignedidentity/azureassignedidentity.go
  test/common/k8s/azureidentity/azureidentity.go
  test/common/k8s/azureidentitybinding/azureidentitybinding.go
  test/common/k8s/azurepodidentityexception/azurepodidentityexception.go
  test/common/k8s/daemonset/daemonset.go
  test/common/k8s/deploy/deploy.go
  test/common/k8s/infra/infra.go
  test/common/k8s/node/node.go
  test/common/k8s/pod/pod.go
  test/e2e/aadpodidentity_test.go
  tools/go.mod
  tools/go.sum
Labels: cleanup
